name: recipe
channels:
    - defaults
dependencies:
  - python=3.10
  - spacy
  - nltk
  - jupyterlab
  - ftfy
  - unidecode
  - inflection
  - requests
  - beautifulsoup4
  - pip
  - html5lib
  - pip:
      - langdetect
      - pandas
      - emoji
      - cairosvg
      - matplotlib
      - scikit-learn
      - rapidfuzz
      - google
      - rasa
      - rasa-sdk
